server:
  port: 1235
spring:
  datasource:
    url: jdbc:mysql://123.206.101.41:3306/im_socket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&useInformationSchema=true
    username: im_socket
    password: S3mkKthLcDtc6p6B
    driver-class-name: com.mysql.jdbc.Driver


beetl:
  suffix: html




